[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "JBxKKoQuM841YxofGvMxCWFiJYUqmE7TTLk6MhNhKtuK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/lbenicio/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
